### ISSUE TITLE
Latest version does not run

### ISSUE THREAD

**Issue by skuid87** [adamgot/python-plexlibrary#110]
Hi - Been using this since Jan2020 without any issues. Plex updates to new agents and suddenly everything stopped working. I did some reading and it looked like some updates have been released to fix the issue. I've retained my original install (which still works if I stick to legacy agents). 

I've created a new folder with the latest gitclone and copied over the config and recipes. However, when I try to run the -h and -l commands to get to the help message and see a list of available recipes. But when I try to run an actual recipe I get the following error:

`$ python3 plexlibrary trending
2021-10-15 22:13:59,621 INFO:Running the recipe 'trending'
2021-10-15 22:13:59,621 INFO:Retrieving the trakt list: https://api.trakt.tv/movies/trending?limit=70≈
2021-10-15 22:13:59,831 INFO:Trying to match with items from the 'Movies' library 
2021-10-15 22:13:59,836 INFO:Trying to match with items from the 'Kids Movies' library 
2021-10-15 22:13:59,840 INFO:Trying to match with items from the 'Bollywood' library 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "plexlibrary/__main__.py", line 8, in <module>
    main()
  File "plexlibrary/plexlibrary.py", line 67, in main
    r.run(sort_only=args.sort_only, share_playlist_to_all=args.everyone)
  File "plexlibrary/recipe.py", line 742, in run
    missing_items, list_count = self._run(share_playlist_to_all=share_playlist_to_all)
  File "plexlibrary/recipe.py", line 683, in _run
    self.source_map.add_libraries(source_libraries)
  File "plexlibrary/recipe.py", line 49, in add_libraries
    self.add_items(library.all())
  File "plexlibrary/recipe.py", line 53, in add_items
    self.add_item(items.pop(0))  # Pop to save on memory
  File "plexlibrary/recipe.py", line 57, in add_item
    guids = self._get_guids(item)
  File "plexlibrary/recipe.py", line 114, in _get_guids
    guids = [guid.id for guid in item.guids]
  File "/usr/local/lib/python3.6/dist-packages/plexapi/base.py", line 280, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Movie' object has no attribute 'guids'
`

**Comment by adamgot** [comment]
You'll also need to upgrade the dependencies (plexapi) to the latest version.
