### ISSUE TITLE
guid log errors on run

### ISSUE THREAD

**Issue by binarylimited** [adamgot/python-plexlibrary#113]
Cant seem to figure out what this error is trying to tell me? is it permissions or something else?

Have install on the dependencies fine.
 
`meh@meh:/opt/python-plexlibrary$ python3 plexlibrary movies_christmas.yml
Sun Nov 28 20:32:58 NZDT 2021
Traceback (most recent call last):
  File "/opt/python-plexlibrary/plexlibrary/plexlibrary.py", line 22, in <module>
    from recipe import Recipe
  File "/opt/python-plexlibrary/plexlibrary/recipe.py", line 148
    logs.warning(f"Unknown guid: {guid}")
                                       ^
SyntaxError: invalid syntax
`

**Comment by adamgot** [comment]
Hi,
What version of python are you running (`python3 --version`), and could you post your recipe file with the sources please.

**Comment by skuid87** [comment]
I'm having the same issues running python 3.7.5

**Comment by skuid87** [comment]
Resolution for me was to run the script using python3.6
