### ISSUE TITLE
Duplicate Library

### ISSUE THREAD

**Issue by cesalo** [adamgot/python-plexlibrary#23]
First of all I think is something related with the version of the script or req or python but not sure how to narrow it down.
I'm running in QNAP my version of python is 2.7.12. I have 2 issues:
1. The Library is created even though already exists. I have 3 "Movie - Trending" library so far.
2. I'm getting the following error at the end:

Scanning the 'Movies - Trending' library...
Traceback (most recent call last):
  File "/opt/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/share/CACHEDEV1_DATA/media/scripts.1/plex.python/python-plexlibrary/plexlibrary/__main__.py", line 3, in <module>
    main()
  File "plexlibrary/plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "plexlibrary/recipe.py", line 648, in run
    missing_items, list_count = self._run()
  File "plexlibrary/recipe.py", line 490, in _run
    new_library.update()
AttributeError: 'MovieSection' object has no attribute 'update'

**Comment by cesalo** [comment]
Solved it. It seems I was using an old version of plexapi. I had to do:
pip uninstall plexapi
pip install plexapi
It seems there is no way to upgrade.

**Comment by adamgot** [comment]
FYI you should be able to do:

    pip install plexapi --upgrade

**Comment by cesalo** [comment]
Nice .. thanks, wasn't aware of that option.
