### ISSUE TITLE
Some symlinks no longer being created

### ISSUE THREAD

**Issue by adzam5** [adamgot/python-plexlibrary#28]
Recently I started noticing some movies in my trending library were "unavailable."  I ran the script manually and and received the same error I see in my log.

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/python-plexlibrary/plexlibrary/__main__.py", line 3, in <module>
    main()
  File "/opt/python-plexlibrary/plexlibrary/plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "/opt/python-plexlibrary/plexlibrary/recipe.py", line 682, in run
    year=item['year']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 29: ordinal not in range(128)
`

**Comment by adamgot** [comment]
Please set this environment variable:

    PYTHONIOENCODING=UTF-8
