### ISSUE TITLE
Unsupported Source List

### ISSUE THREAD

**Issue by aibradford** [adamgot/python-plexlibrary#30]
I keep getting this for every other list i try to make that isnt one of the examples that came with the program.

Can anyone advise what is wrong?

C:\_dls\python-plexlibrary>python plexlibrary Reddittop250
Running the recipe 'Reddittop250'
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\_dls\python-plexlibrary\plexlibrary\__main__.py", line 3, in <module>
    main()
  File "plexlibrary\plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "plexlibrary\recipe.py", line 673, in run
    missing_items, list_count = self._run()
  File "plexlibrary\recipe.py", line 76, in _run
    url=url))
Exception: Unsupported source list: https://trakt.tv/users/philrivers/lists/reddit-top-250-2017-edition

**Comment by adamgot** [comment]
You need to specify the API URL for the list (at least until I make it automatically convert...)

Correct URL would be 

    https://api.trakt.tv/users/philrivers/lists/reddit-top-250-2017-edition/items/movies
