### ISSUE TITLE
Unable to load trending lists

### ISSUE THREAD

**Issue by aibradford** [adamgot/python-plexlibrary#31]
I get an error about a bsddb.db file im missing. I reinstalled bsddb and still getting same error.

Little help?

C:\_dls\python-plexlibrary>PYTHON PLEXLIBRARY movies_trending
Running the recipe 'movies_trending'
Retrieving the trakt list: https://api.trakt.tv/movies/trending?limit=2
Retrieving the trakt list: https://api.trakt.tv/movies/watched/weekly?limit=100
Retrieving the trakt list: https://api.trakt.tv/movies/trending?limit=50
Retrieving the trakt list: https://api.trakt.tv/movies/watched/monthly?limit=150
Retrieving the trakt list: https://api.trakt.tv/movies/watched/yearly?limit=500
Getting data from TMDb to add weighted sorting...
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\_dls\python-plexlibrary\PLEXLIBRARY\__main__.py", line 3, in <module>
    main()
  File "PLEXLIBRARY\plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "PLEXLIBRARY\recipe.py", line 673, in run
    missing_items, list_count = self._run()
  File "PLEXLIBRARY\recipe.py", line 81, in _run
    item_list = self.weighted_sorting(item_list)
  File "PLEXLIBRARY\recipe.py", line 735, in weighted_sorting
    details = self.tmdb.get_details(m['tmdb_id'], self.library_type)
  File "PLEXLIBRARY\tmdb.py", line 66, in get_details
    cache = shelve.open(self.cache_file)
  File "C:\Python27\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "C:\Python27\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "C:\Python27\lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "C:\Python27\lib\dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "C:\Python27\lib\bsddb\__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')

**Comment by adamgot** [comment]
What does you config.yml file look like?

**Comment by memnos** [comment]
I have this problem too.
i give:
`python plexlibrary/plexlibrary.py movies_trending
Running the recipe 'movies_trending'
Retrieving the trakt list: https://api.trakt.tv/movies/trending?limit=2
Retrieving the trakt list: https://api.trakt.tv/movies/watched/weekly?limit=100
Retrieving the trakt list: https://api.trakt.tv/movies/trending?limit=50
Retrieving the trakt list: https://api.trakt.tv/movies/watched/monthly?limit=150
Retrieving the trakt list: https://api.trakt.tv/movies/watched/yearly?limit=500
Warning: TMDd API key is required for weighted sorting
Trying to match with items from the 'Film' library
`
Now it begins to list movies, after movie number 113 i have this error.

`Traceback (most recent call last):
  File "plexlibrary/plexlibrary.py", line 67, in <module>
    main()
  File "plexlibrary/plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "/root/scripts/plexlibrary/plexlibrary/recipe.py", line 687, in run
    missing_items, list_count = self._run()
  File "/root/scripts/plexlibrary/plexlibrary/recipe.py", line 141, in _run
    if r.guid is not None and 'imdb://' in r.guid:
  File "/usr/local/lib/python2.7/dist-packages/plexapi/base.py", line 284, in __getattribute__
    self.reload()
  File "/usr/local/lib/python2.7/dist-packages/plexapi/base.py", line 189, in reload
    data = self._server.query(key)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 341, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=32400): Read timed out. (read timeout=30)
`

My Config.yml is like this:
`# Plex server details
# * Defaults to plexapi config
plex:
    baseurl: 'http://localhost:32400'
    token: 'XXX'  # https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

# trakt.tv API details
# * Required for fetching trakt lists
# Create a Trakt.tv account, then create an API app here:
# https://trakt.tv/oauth/applications/new
trakt:
    username: 'MY_USER'
    client_id: 'XXX'
    client_secret: 'XXX'
    oauth_token: 'XXX'  # Filled in later depending on recipe

# The Movie Database details
# * Required for fetching scores, release dates etc for weighted sorting
# * Required for matching any library items that use the TMDb agent with the items from the lists
#   (if those items do not include a TMDb ID)
tmdb:
    api_key: ''
    cache_file: '/tmp/tmdb_details.shelve'

# TheTVDB details
# * Required for matching any library items that use the TheTVDB agent with the items from the lists
#   (if those items do not include a TheTVDB ID)
tvdb:
    username: ''
    api_key: ''
    user_key: ''
`
