### ISSUE TITLE
Keep getting "OAuth must be provided"

### ISSUE THREAD

**Issue by Landelor** [adamgot/python-plexlibrary#39]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/plexlibrary/plexlibrary/__main__.py", line 3, in <module>
    main()
  File "plexlibrary/plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "plexlibrary/recipe.py", line 687, in run
    missing_items, list_count = self._run()
  File "plexlibrary/recipe.py", line 78, in _run
    self.recipe['new_library']['max_age'] or 0)
  File "plexlibrary/traktutils.py", line 138, in add_items
    movie_ids=item_ids, max_age=max_age)
  File "plexlibrary/traktutils.py", line 70, in add_movies
    movie_data = self._handle_request('get', url, data=data)
  File "plexlibrary/traktutils.py", line 54, in _handle_request
    raise self.trakt_core.error_map[response.status_code]()
trakt.errors.OAuthException: Unauthorized - OAuth must be provided

I've tried multiple ways of adding the token.

**Comment by adamgot** [comment]
I can't seem to refresh my OAuth token right now either, seems like something has changed on the Trakt side. I'll have to look into it some more.

**Comment by adamgot** [comment]
This should only affect things like the personal recommendation lists though.

**Comment by scottmccaughey** [comment]
Was this issue ever resolved? I'm getting the same error when I try to access my Watchlist.

**Comment by antigravity83** [comment]
Same. Get this error when trying to pull recommendations. 

Oath seems to be fine when pulling from other lists.

**Comment by adamgot** [comment]
Haven’t had time to look into this, sorry.

OAuth authorisation is only used for getting data tied to your personal account, so anything else should work.

**Comment by adamgot** [comment]
Should be fixed now. Error occured when OAuth token expired, it will now ask to authenticate again.

Will need to install dependencies again. pip install -r requirements.txt
