### ISSUE TITLE
Unable to use own private list

### ISSUE THREAD

**Issue by EnorMOZ** [adamgot/python-plexlibrary#54]
```Traceback (most recent call last):
  File "/opt/python-plexlibrary/plexlibrary/plexlibrary.py", line 67, in <module>
    main()
  File "/opt/python-plexlibrary/plexlibrary/plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "/opt/python-plexlibrary/plexlibrary/recipe.py", line 690, in run
    missing_items, list_count = self._run()
  File "/opt/python-plexlibrary/plexlibrary/recipe.py", line 79, in _run
    self.recipe['new_library']['max_age'] or 0)
  File "/opt/python-plexlibrary/plexlibrary/traktutils.py", line 152, in add_items
    movie_ids=item_ids, max_age=max_age)
  File "/opt/python-plexlibrary/plexlibrary/traktutils.py", line 84, in add_movies
    movie_data = self._handle_request('get', url, data=data)
  File "/opt/python-plexlibrary/plexlibrary/traktutils.py", line 68, in _handle_request
    raise self.trakt_core.error_map[response.status_code]()

**Comment by EnorMOZ** [comment]
Was missing `trakt_oauth: true` from the config
