### ISSUE TITLE
HTTPConnectionPool Timeouts

### ISSUE THREAD

**Issue by sbcrumb** [adamgot/python-plexlibrary#55]
This is a consistent error. now if I leave it sit it will some times resolve it self.
Not sure how to fix it or troubleshoot it.

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/python-plexlibrary/plexlibrary/__main__.py", line 3, in <module>
    main()
  File "plexlibrary/plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "plexlibrary/recipe.py", line 690, in run
    missing_items, list_count = self._run()
  File "plexlibrary/recipe.py", line 142, in _run
    if r.guid is not None and 'imdb://' in r.guid:
  File "/usr/local/lib/python2.7/dist-packages/plexapi/base.py", line 290, in __getattribute__
    self.reload()
  File "/usr/local/lib/python2.7/dist-packages/plexapi/base.py", line 195, in reload
    data = self._server.query(key)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 343, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=32400): Read timed out. (read timeout=30)

**Comment by theguypeter** [comment]
!Solved 
My Drive was mounted with Rlone Cache.

Are you using Rclone Cache or a normal Mount of  Google drive? 

Mount with:

`rclone mount Gdrive: ~/gdrive \
   --allow-other \
   --dir-cache-time=24h \
   --cache-db-purge \
   --cache-db-path=/dev/shm/rclone/ \
   --cache-chunk-path=/home/darthshadow/ssd/ \
   --cache-workers=4 \
   --cache-tmp-upload-path=/home/darthshadow/rclone/tmp_upload/ \
   --cache-tmp-wait-time=6h \
   --cache-chunk-size=128M \
   --cache-chunk-total-size=75G \
   --cache-chunk-clean-interval=300s \
   --cache-info-age=36h \
   --drive-chunk-size=32M \
   --fast-list \
   --vfs-read-chunk-size=256M \
   --vfs-read-chunk-size-limit=off \
   --vfs-cache-mode=writes \
   --vfs-cache-max-age=3h \
   --vfs-cache-poll-interval=1m \
   --cache-dir=/home/darthshadow/rclone/ \
   --buffer-size=0 \
   --attr-timeout=1s \
   --umask 002 \
   --rc \
   --log-file=/home/darthshadow/rclone/rclone.log \
   --stats=1m \
   --stats-log-level=NOTICE \
   -v'
