### ISSUE TITLE
ImportError: No module named ruamel.yaml

### ISSUE THREAD

**Issue by Hawkinzzz** [adamgot/python-plexlibrary#68]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/appdata/python-plexlibrary/plexlibrary/__main__.py", line 2, in <module>
    from plexlibrary import main
  File "plexlibrary/plexlibrary.py", line 21, in <module>
    import recipes
  File "plexlibrary/recipes.py", line 5, in <module>
    from utils import YAMLBase
  File "plexlibrary/utils.py", line 4, in <module>
    import ruamel.yaml
ImportError: No module named ruamel.yaml

**Comment by Hawkinzzz** [comment]
I had to run it using python3

**Comment by mariotacke** [comment]
Related to #71. Missing dependency `mock`.
