### ISSUE TITLE
Error when running python plexlibrary -l / -h

### ISSUE THREAD

**Issue by cwilcoxc** [adamgot/python-plexlibrary#71]
I'm probably doing something basic wrong in setting this up.
All files stored locally in root directory: `cd /opt/appdata/pydpl/$`
Recipes have been setup and are contained in `/opt/appdata/pydpl/recipes/`
When I run `python plexlibrary -l` I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/appdata/pydpl/plexlibrary/__main__.py", line 2, in <module>
    from plexlibrary import main
  File "plexlibrary/plexlibrary.py", line 22, in <module>
    from recipe import Recipe
  File "plexlibrary/recipe.py", line 13, in <module>
    import plexapi
  File "/home/timmeh/.local/lib/python2.7/site-packages/plexapi/__init__.py", line 6, in <module>
    from plexapi.config import PlexConfig, reset_base_headers
  File "/home/timmeh/.local/lib/python2.7/site-packages/plexapi/config.py", line 4, in <module>
    from plexapi.compat import ConfigParser
  File "/home/timmeh/.local/lib/python2.7/site-packages/plexapi/compat.py", line 50, in <module>
    from mock import patch, MagicMock
ImportError: No module named mock
```

Python version 2.7.17
Pip 20.0.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

Cheers!

**Comment by cwilcoxc** [comment]
SOLVED - installed mock
`pip install mock`

**Comment by mariotacke** [comment]
Ran into the same. Looks to be a missing dependency in `requirements.txt`.

**Comment by adamgot** [comment]
Looks like plexapi was missing the dependency. I’d advice starting to use python 3 from now on as more and more 3rd party libs have dropped support for 2.
