### ISSUE TITLE
ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by typo2014** [adamgot/python-plexlibrary#77]
Hi 

Installed based on wiki on ubuntu 18.04 
everything up2date 

whenever i try to run any command 
e.g.  python3 plexlibrary -l

i get the following error: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "plexlibrary/__main__.py", line 2, in <module>
    from plexlibrary import main
  File "plexlibrary/plexlibrary.py", line 21, in <module>
    import recipes
  File "plexlibrary/recipes.py", line 5, in <module>
    from utils import YAMLBase
  File "plexlibrary/utils.py", line 4, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'
```

i also installed mock as it was recommended as a possible solution but i still get the same error 

Any idea how to solve it? 

all the best
Typo

**Comment by justinglock40** [comment]
`sudo apt-get install python3-dev`

`pip install ruamel.yaml`

`pip3 install ruamel.yaml` if using Python3

**Comment by chiggerz** [comment]
hi, did this resolve for OP as I am having the same issue. Tried the above, but still getting same error:
 File "plexlibrary/utils.py", line 4, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'

any help would be greatly appreciated, its frying my brain :-)

**Comment by AndyLow91** [comment]
I've suddenly come up against this issue now after successfully running the script as a cron job for around 3 months. I've tried the suggestion above but only receive an error stating that ruamel.yml is already installed. Does anyone have any other suggestions for a fix?

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/carrotsoup/pyplex/plexlibrary/__main__.py", line 2, in <module>
    from plexlibrary import main
  File "/home/carrotsoup/pyplex/plexlibrary/plexlibrary.py", line 21, in <module>
    import recipes
  File "/home/carrotsoup/pyplex/plexlibrary/recipes.py", line 7, in <module>
    from utils import YAMLBase
  File "/home/carrotsoup/pyplex/plexlibrary/utils.py", line 4, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'
`
