### ISSUE TITLE
Error creating symlinks

### ISSUE THREAD

**Issue by Hawkinzzz** [adamgot/python-plexlibrary#87]
I left this project running automatically once a week to update the trending movies and trending series libraries and it was working perfectly without a hitch! but then recently I noticed the lists had stopped changing. when I run the code manually I get an error when creating symlinks. I have run it a few times and still the same error. I noticed you had been working on the scripts, great! I updated my .py files to suit but still the same issue. I have a feeling this is something I am doing wrong but for the life of me I cannot figure out what!?

This is the error I am getting

`Traceback (most recent call last):
  File "plexlibrary.py", line 67, in <module>
    main()
  File "plexlibrary.py", line 61, in main
    r.run(args.sort_only)
  File "/opt/appdata/python-plexlibrary/plexlibrary/recipe.py", line 637, in run
    missing_items, list_count = self._run()
  File "/opt/appdata/python-plexlibrary/plexlibrary/recipe.py", line 605, in _run
    self._create_symbolic_links(matching_items=matching_items, matching_total=matching_total)
  File "/opt/appdata/python-plexlibrary/plexlibrary/recipe.py", line 241, in _create_symbolic_links
    os.rmdir(new_path)
NotADirectoryError: [Errno 20] Not a directory: '/mnt/plexlib/movies/Movies - Trending/Invasion (2020)'`

I have used /mnt/plexlib for my dynamic library locations (for symlinks).

I have tried to remove all the files/symlinks created and run the script again but it always stops on this folder (when I clear the folders and run the script it runs for longer like its doing something but then stops here again).

Any help or direction would be appreciated!

**Comment by Hawkinzzz** [comment]
Nevermind, it seems that the two files it had an issue with it didn't like so I replaced them and now it works :)
