### ISSUE TITLE
New install .. keeps creating the same library

### ISSUE THREAD

**Issue by Radikaltimes** [adamgot/python-plexlibrary#88]
i ran python3 plexlibrary hulu .. it created the library and started to populate it .. got around 74 shows and error out.
.. about 2 hours later started again and created another library with the same name.
i have no setup any cron ...

any ideas?

**Comment by Radikaltimes** [comment]
here is the error.
`Setting` the sort titles for the 'TV Shows Hulu' library...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "plexlibrary/__main__.py", line 3, in <module>
    main()
  File "plexlibrary/plexlibrary.py", line 64, in main
    r.run(args.sort_only)
  File "plexlibrary/recipe.py", line 637, in run
    missing_items, list_count = self._run()
  File "plexlibrary/recipe.py", line 613, in _run
    all_new_items = self._modify_sort_titles_and_cleanup(item_list=item_list, imdb_map=imdb_map, new_library=new_library, sort_only=False)
  File "plexlibrary/recipe.py", line 438, in _modify_sort_titles_and_cleanup
    return all_new_items
UnboundLocalError: local variable 'all_new_items' referenced before assignment

**Comment by Radikaltimes** [comment]
100% my fault
