### ISSUE TITLE
Python JSON Decode error

### ISSUE THREAD

**Issue by antigravity83** [adamgot/python-plexlibrary#91]
Script has been working fine - running on daily cron like a dream. Until today

No changes have been made. All recipes, Movie or TV don't work. 

Ubuntu Server 18.04

```
Traceback (most recent call last):
  File "plexlibrary.py", line 70, in <module>
    main()
  File "plexlibrary.py", line 63, in main
    r = Recipe(recipe_name=args.recipe, use_playlists=args.playlists)
  File "/opt/appdata/plexlibrary/plexlibrary/recipe.py", line 57, in __init__
    config=self.config)
  File "/opt/appdata/plexlibrary/plexlibrary/traktutils.py", line 25, in __init__
    client_secret=client_secret)
  File "/home/media/.local/lib/python3.6/site-packages/trakt/core.py", line 136, in pin_auth
    OAUTH_TOKEN = response.json().get('access_token', None)
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by antigravity83** [comment]
Sorry... Nevermind. Trakt is down!
