### ISSUE TITLE
Won't match when creating new TV Library

### ISSUE THREAD

**Issue by timmehtimtims** [adamgot/python-plexlibrary#99]
I've just updated to the latest Plex server build: 1.21.0.3616

`user@Ubuntu-1804-bionic-64-minimal:/opt/appdata/python-plexlibrary$ sudo python3 plexlibrary tv_cartoons
2020-11-24 12:35:00,719 INFO:Running the recipe 'tv_cartoons'
2020-11-24 12:35:00,719 INFO:Retrieving the trakt list: https://api.trakt.tv/users/kylesheila/lists/kids-cartoons/items/tv
2020-11-24 12:35:00,879 INFO:Trying to match with items from the 'TV Shows' library 
2020-11-24 12:35:00,887 INFO:Creating symlinks for 0 matching items in the library...
2020-11-24 12:35:00,887 INFO:Created symlinks for 0 new items:
2020-11-24 12:35:00,888 INFO:Creating the 'TV - Kids Cartoons' library in Plex...
2020-11-24 12:35:00,893 WARNING:Library already exists in Plex. Scanning the library...
2020-11-24 12:35:00,896 INFO:Waiting for metadata to finish downloading...
2020-11-24 12:35:00,902 INFO:Retrieving a list of items from the 'TV - Kids Cartoons' library in Plex...
2020-11-24 12:35:00,905 INFO:Setting the sort titles for the 'TV - Kids Cartoons' library...
2020-11-24 12:35:00,905 INFO:Scanning the 'TV - Kids Cartoons' library...
^[[A^[[A2020-11-24 12:35:10,940 INFO:Number of items in the new library: 0
2020-11-24 12:35:10,940 INFO:Number of missing items: 0`

If I run the exact same recipe same with a list that I have already setup, then it is able to match with the 'TV Shows' library and remove/add new symlinks. However any new TV libraries won't match and it creates 0 symlinks.

**Comment by timmehtimtims** [comment]
Here is my YAML file. If anyone else can run this recipe then I know it's an issue with my install.

`# Supported types: movie, tv
library_type: 'tv'

# Source list(s)
# * Experiment with the limits and order of the URLs below
#   to get a different balance.
source_list_urls:
  - 'https://api.trakt.tv/users/kylesheila/lists/kids-cartoons/items/tv'
  - 'https://api.trakt.tv/users/rendom/lists/memory-lane-cartoons-80-s/items/tv/'
  - 'https://api.trakt.tv/users/leia18/lists/kids-cartoons/items/tv'
  - 'https://api.trakt.tv/users/ondrisel/lists/classic-cartoons/items/tv'
  - 'https://api.trakt.tv/users/fiala06/lists/saturday-morning-cartoons/items/tv/'

# Source library details
source_libraries:
  - name: 'TV Shows'
    folders:
      - '/mnt/unionfs/tv/'

# New library details
new_library:
  name: 'TV - Kids Cartoons'
  folder: '/mnt/lists/cartoons/'
  sort: false
  sort_title:
    format: '{number}. {title}'
    visible: false
    absolute: false  # Skips numbers for missing items
  # Limit the age (in years) of items to be considered
  # * 0 for no limit
  max_age: 0
  # Maximum number of items to keep in the library
  max_count: 2000
  # Remove items that no longer exist in the source lists
  remove_from_library: false

# Weighted sorting (requires TMDb API)
weighted_sorting:
  enabled: false
  better_release_date: false
  weights:
    # Think of these as percentages,
    # but they don't have to add up to 1.0
    # * Additive
    # * Higher value -> more important
    index: 0.75
    vote: 0.10
    age: 0.15
    random: 0.0
    # Penalize (<0) or reward (>0) certain (TMDb) genres
    # * Final weight is multiplied by these values
    genre_bias:
      'Kids': 0.9
`

**Comment by timmehtimtims** [comment]
Now generating error:

```
2020-12-20 14:23:46,230 INFO:Running the recipe 'tv_kids_cartoons'
2020-12-20 14:23:46,231 INFO:Retrieving the trakt list: https://api.trakt.tv/users/leia18/lists/kids-cartoons/items/tv/
2020-12-20 14:23:46,387 INFO:Retrieving the trakt list: https://api.trakt.tv/users/kylesheila/lists/kids-cartoons/items/tv/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "plexlibrary/__main__.py", line 8, in <module>
    main()
  File "plexlibrary/plexlibrary.py", line 67, in main
    r.run(sort_only=args.sort_only, share_playlist_to_all=args.everyone)
  File "plexlibrary/recipe.py", line 654, in run
    missing_items, list_count = self._run(share_playlist_to_all=share_playlist_to_all)
  File "plexlibrary/recipe.py", line 588, in _run
    item_list, item_ids = self._get_trakt_lists()
  File "plexlibrary/recipe.py", line 91, in _get_trakt_lists
    max_age or 0)
  File "plexlibrary/traktutils.py", line 155, in add_items
    show_ids=item_ids, max_age=max_age)
  File "plexlibrary/traktutils.py", line 125, in add_shows
    if m['show']['ids']['imdb'] in show_ids:
KeyError: 'ids'
```

**Comment by chiggerz** [comment]
did you ever get this working? im getting the same thing. created new legacy library so I know its not using the new agent, but saying that, is this now no longer working at all? or is it still working when using legacy agent?

**Comment by timmehtimtims** [comment]
Not working for me still unfortunately. I ended up going into sonarr, tagging those shows and then moving that list into a new directory and then created a new library from that dir...

**Comment by chiggerz** [comment]
> Not working for me still unfortunately. I ended up going into sonarr, tagging those shows and then moving that list into a new directory and then created a new library from that dir...

Ive gone down the auto collections route now.  same as this but collections rather than libraries.  not ideal, and not what I really wanted, but its a work around and something to use until this is working again

**Comment by morganzero** [comment]
> > Not working for me still unfortunately. I ended up going into sonarr, tagging those shows and then moving that list into a new directory and then created a new library from that dir...
> 
> Ive gone down the auto collections route now. same as this but collections rather than libraries. not ideal, and not what I really wanted, but its a work around and something to use until this is working again

I can confirm that it is still working with Legacy as I never switched agents and the script is still working for me.
